name: tfsec

on:
  pull_request:
  push:
  schedule:
    - cron: 41 20 * * 2

jobs:
  tfsec:
    permissions:
      actions: read
      contents: read
      security-events: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
